spring.application.name=listener
server.port=8081

# Banco de Dados
spring.datasource.url=jdbc:postgresql://localhost:5432/pedido_db
spring.datasource.username=myuser
spring.datasource.password=mypassword
spring.jpa.hibernate.ddl-auto=update

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Redis
spring.redis.host=localhost
spring.redis.port=6379