spring.application.name=consultation
server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/pedido_db
spring.datasource.username=myuser
spring.datasource.password=mypassword
spring.jpa.hibernate.ddl-auto=update